#!/bin/bash


#ANTLR
CLASSPATH=".:~/.local/lib/java/antlr-4.7.2-complete.jar:$CLASSPATH"
alias antlr4='java -jar ~/.local/lib/java/antlr-4.7.2-complete.jar'
alias grun='java org.antlr.v4.gui.TestRig'
