#!/bin/bash

shopt -s expand_aliases
source ./setup_env

echo generating files
antlr4 Cdl.g4
echo done
javac *.java
#grun Cdl cdl_file test_cruise.cdl -tokens -gui
./cdl_preprocessor.py < test_cruise.cdl |  grun Cdl cdl_file test.tmp -tokens -gui
